// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4l15IlK39A0dXm_E9fu4C89BDBD0rbkw',
    appId: '1:934008395061:web:56d10ad344fdae65f6287c',
    messagingSenderId: '934008395061',
    projectId: 'it-avenue-dealers-portal',
    authDomain: 'it-avenue-dealers-portal.firebaseapp.com',
    storageBucket: 'it-avenue-dealers-portal.appspot.com',
    measurementId: 'G-FVG3CTSLLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjVIm3dIiPheP3K1JHT1-3937ClM8H1c8',
    appId: '1:934008395061:android:bff2f5227d2521abf6287c',
    messagingSenderId: '934008395061',
    projectId: 'it-avenue-dealers-portal',
    storageBucket: 'it-avenue-dealers-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwz_PmzVtZi6_V1UD0K1NCgVrpZj-N3pg',
    appId: '1:934008395061:ios:8c339f9b2e006430f6287c',
    messagingSenderId: '934008395061',
    projectId: 'it-avenue-dealers-portal',
    storageBucket: 'it-avenue-dealers-portal.appspot.com',
    androidClientId:
        '934008395061-74ip28moqm59erb4sskofvfmh13o05eb.apps.googleusercontent.com',
    iosClientId:
        '934008395061-mqkb8tdemb5lqhn31ad5bpo9b94p96vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.itavenueWeb',
  );
}
